name: Feature request
description: Suggest a new feature or idea
labels: [enhancement]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Summary
      description: An explanation of your feature suggestion
    id: description
    
