name: Negative feedback
description: File a feedback report
title: Describe what went poorly
labels: [feedback]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Problem Description
      description: Please enter a description of the issue.
    id: description
  - type: textarea
    validations:
      required: true
    attributes:
      label: Steps To Reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
    id: steps
  - type: textarea
    attributes:
      label: Expected Results
      description: Describe what you expected to happen.
    id: expected
  - type: input
    validations:
      required: true
    attributes:
      label: App version
      description: |
        Look in the About dialog to find this
    id: version
    