name: Negative feedback
description: File a feedback report
title: Describe what went poorly
labels: [feedback]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Prompt
      description: What did you ask?
    id: prompt
  - type: textarea
    validations:
      required: true
    attributes:
      label: Response
      description: What was the response?
    id: response
  - type: checkboxes
    attributes:
      label: What was the problem with the response?
      options:
        - label: This is harmful / unsafe
        - label: This isn't true
        - label: This isn't helpful
    id: problems
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected
      description: What would the ideal answer have been?
    id: expected
  - type: input
    validations:
      required: true
    attributes:
      label: App version
      description: |
        Look in the About dialog to find this
    id: version
    