name: Positive feedback
description: File a feedback report
title: Describe what went well
labels: [feedback]
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Prompt
      description: What did you ask?
    id: prompt
  - type: textarea
    validations:
      required: true
    attributes:
      label: Response
      description: What was the response?
    id: response
  - type: textarea
    validations:
      required: true
    attributes:
      label: Expected
      description: What would the ideal answer have been?
    id: expected
  - type: input
    validations:
      required: true
    attributes:
      label: App version
      description: |
        Look in the About dialog to find this
    id: version
    